name: BeautySurroundsYou
favicon: null
layout_spectrum: 0.85216
typography_spectrum: 0.09791
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffeff'
    - '#202131'
    - '#505251'
    - '#e5c700'
    - '#5083a6'
  brandStrength: 0.125
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
